version: '3.3'
services:
  orion-visor-service:
    image: registry.cn-hangzhou.aliyuncs.com/lijiahangmax/orion-visor-service:2.0.0
    ports:
      - 1081:80
    environment:
      - MYSQL_HOST=orion-visor-mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=orion_visor
      - MYSQL_USER=orion
      - MYSQL_PASSWORD=Data@123456
      - REDIS_HOST=orion-visor-redis
      - REDIS_PASSWORD=Data@123456
      - SECRET_KEY=uQeacXV8b3isvKLK
    volumes:
      - /data/orion-visor-space/docker-volumes/orion-visor-service/logs:/root/orion/logs/orion-visor
      - /data/orion-visor-space/docker-volumes/orion-visor-service/app:/root/orion/orion-visor
    depends_on:
      - orion-visor-mysql
      - orion-visor-redis
  orion-visor-mysql:
    image: registry.cn-hangzhou.aliyuncs.com/lijiahangmax/orion-visor-mysql:2.0.0
    privileged: true
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=orion_visor
      - MYSQL_USER=orion
      - MYSQL_PASSWORD=Data@123456
      - MYSQL_ROOT_PASSWORD=Data@123456
    volumes:
      - /data/orion-visor-space/docker-volumes/orion-visor-mysql/var-lib-mysql:/var/lib/mysql
      - /data/orion-visor-space/docker-volumes/orion-visor-mysql/var-lib-mysql-files:/var/lib/mysql-files
      - /data/orion-visor-space/docker-volumes/orion-visor-mysql/etc-mysql:/etc/mysql
  orion-visor-redis:
    image: registry.cn-hangzhou.aliyuncs.com/lijiahangmax/orion-visor-redis:2.0.0
    privileged: true
    ports:
      - 6380:6379
    environment:
      - REDIS_PASSWORD=Data@123456
    volumes:
      - /data/orion-visor-space/docker-volumes/orion-visor-redis/data:/data
      - /data/orion-visor-space/docker-volumes/orion-visor-redis/usr-local-etc-redis:/usr/local/etc/redis
    command: sh -c "redis-server /usr/local/etc/redis/redis.conf --requirepass $${REDIS_PASSWORD}"
  orion-visor-adminer:
    image: adminer
    ports:
      - 8081:8080
