spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/orion-ops-pro?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: root
      password: Data@123456
      initial-size: 0
      min-idle: 1
      max-active: 5
  redis:
    host: 127.0.0.1
    port: 6379
    password: Data@123456
  redisson:
    threads: 2
    netty-threads: 2

mybatis-plus:
  configuration:
    # 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
