spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/orion-ops-pro?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: root
      password: Data@123456
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
      filter:
        stat:
          enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: lijiahang
    timeout: 3000

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

knife4j:
  enable: false

orion:
  logging:
    printer:
      mode: ROW
  crypto:
    aes:
      # 加密秘钥
      secret-key: uQeacXV8b3isvKLK
  thread:
    pool:
      core-pool-size: 8
      max-pool-size: 16
      queue-capacity: 200
      keep-alive-seconds: 300
