name: 功能改进
description: 提出新功能建议 (请提交到需求收集帖)
title: "[功能建议]: "
labels: [ "" ]
body:
  - type: markdown
    attributes:
      value: |
        所有功能建议请统一提交到需求收集帖: 🔗 [#83 需求收集](https://github.com/dromara/orion-visor/issues/83)

        在提交前请确认:
        - ✅ 使用的是[最新版本](https://github.com/dromara/orion-visor/releases)
        - ✅ 已搜索[已有 issue](https://github.com/dromara/orion-visor/issues) 和 需求收集帖避免重复
        - ✅ 定制化需求请联系作者

        ---
        
        ### 如何提交高质量建议？
        1. **功能描述**: 你希望增加什么？
        2. **使用场景**: 你在什么情况下需要它？
        4. **参考实现**: 开源项目中的类似功能（**禁止引用商业闭源软件**）
  - type: textarea
    id: feature
    attributes:
      label: 功能改进
      description: 请详细描述需要改进或者添加的功能。
      placeholder: "功能改进"
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: 参考资料
      description: 可以列举一些参考资料, 但是不要引用同类但商业化软件的任何内容。
      placeholder: "参考资料"