spring:
  datasource:
    druid:
      url: jdbc:mysql://116.62.194.246:3306/orion_visor?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: root
      password: LjhData@123456
      initial-size: 0
      min-idle: 1
      max-active: 5
  redis:
    host: 116.62.194.246
    port: 6379
    password: Ljhlijiahang
  redisson:
    threads: 2
    netty-threads: 2

mybatis-plus:
  configuration:
    # 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
