spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/orion_visor?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: root
      password: Data@123456
      initial-size: 0
      min-idle: 1
      max-active: 5
      stat-view-servlet:
        enabled: false
  redis:
    host: 127.0.0.1
    port: 6379
    password: Data@123456
  redisson:
    threads: 2
    netty-threads: 2
    minimum-idle-size: 2
  boot:
    admin:
      client:
        enabled: false
      server:
        enabled: false

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: shutdown

mybatis-plus:
  configuration:
    # sql 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
