spring:
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:orion_visor}?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: ${MYSQL_USER:root}
      password: ${MYSQL_PASSWORD:Data@123456}
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 20
      # 控制台
      stat-view-servlet:
        enabled: true
        login-username: ${DRUID_USERNAME:admin}
        login-password: ${DRUID_PASSWORD:admin}
      web-stat-filter:
        enabled: true
      filter:
        stat:
          enabled: true
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:Data@123456}
    database: ${REDIS_DATABASE:0}
    data-version: ${REDIS_DATA_VERSION:1}
  redisson:
    threads: 4
    netty-threads: 4
    minimum-idle-size: 4
  influxdb:
    enabled: ${INFLUXDB_ENABLED:true}
    url: http://${INFLUXDB_HOST:127.0.0.1}:${INFLUXDB_PORT:8086}
    org: ${INFLUXDB_ORG:orion-visor}
    bucket: ${INFLUXDB_BUCKET:metrics}
    token: ${INFLUXDB_TOKEN:Data@123456}
  quartz:
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 10
  boot:
    admin:
      client:
        enabled: true
      server:
        enabled: true

guacd:
  host: ${GUACD_HOST:127.0.0.1}
  port: ${GUACD_PORT:4822}
  drive-path: ${GUACD_DRIVE_PATH:/usr/share/guacd/drive}

management:
  endpoints:
    enabled-by-default: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

knife4j:
  enable: false
  production: true

orion:
  # 是否为演示模式
  demo: ${DEMO_MODE:false}
  api:
    # 是否允许跨域
    cors: ${API_CORS:true}
    expose:
      # 暴露接口请求头值
      token: ${API_EXPOSE_TOKEN:pmqeHOyZaumHm0Wt}
  logging:
    printer:
      mode: PRETTY
  encrypt:
    aes:
      # 加密密钥
      secret-key: ${SECRET_KEY:uQeacXV8b3isvKLK}
  async:
    executor:
      core-pool-size: 8
      max-pool-size: 16
      queue-capacity: 200
      keep-alive-seconds: 300
